
Training with beta_scale: 1e-05 and penalty_scale: 1e-10
























Step 250 of 500; Loss: 4.6445e+04. Model Size: 8610 (Time: 235.8s)
Exception ignored in: <function _xla_gc_callback at 0x2b12dfe9fa60>
Traceback (most recent call last):
  File "/home/xz3013/.conda/envs/yolanda/lib/python3.9/site-packages/jax/_src/lib/__init__.py", line 96, in _xla_gc_callback
    def _xla_gc_callback(*args):





Step 300 of 500; Loss: 4.5360e+04. Model Size: 8610 (Time: 265.2s)
Exception ignored in: <function _xla_gc_callback at 0x2b12dfe9fa60>
Traceback (most recent call last):
  File "/home/xz3013/.conda/envs/yolanda/lib/python3.9/site-packages/jax/_src/lib/__init__.py", line 96, in _xla_gc_callback
    def _xla_gc_callback(*args):

Step 310 of 500; Loss: 4.5285e+04. Model Size: 8610 (Time: 271.0s)
Exception ignored in: <function _xla_gc_callback at 0x2b12dfe9fa60>
Traceback (most recent call last):
  File "/home/xz3013/.conda/envs/yolanda/lib/python3.9/site-packages/jax/_src/lib/__init__.py", line 96, in _xla_gc_callback
    def _xla_gc_callback(*args):
KeyboardInterrupt:
Exception ignored in: <function _xla_gc_callback at 0x2b12dfe9fa60>
Traceback (most recent call last):
  File "/home/xz3013/.conda/envs/yolanda/lib/python3.9/site-packages/jax/_src/lib/__init__.py", line 96, in _xla_gc_callback
    def _xla_gc_callback(*args):
KeyboardInterrupt:
Exception ignored in: <function _xla_gc_callback at 0x2b12dfe9fa60>
Traceback (most recent call last):
  File "/home/xz3013/.conda/envs/yolanda/lib/python3.9/site-packages/jax/_src/lib/__init__.py", line 96, in _xla_gc_callback
    def _xla_gc_callback(*args):




