2024-08-30 00:35:19,085 INFO    MainThread:1294756 [wandb_setup.py:_flush():77] Current SDK version is 0.17.8
2024-08-30 00:35:19,085 INFO    MainThread:1294756 [wandb_setup.py:_flush():77] Configure stats pid to 1294756
2024-08-30 00:35:19,085 INFO    MainThread:1294756 [wandb_setup.py:_flush():77] Loading settings from /home/rsw0/.config/wandb/settings
2024-08-30 00:35:19,085 INFO    MainThread:1294756 [wandb_setup.py:_flush():77] Loading settings from /home/rsw0/Desktop/yolanda/temp/CogModRNN/wandb/settings
2024-08-30 00:35:19,085 INFO    MainThread:1294756 [wandb_setup.py:_flush():77] Loading settings from environment variables: {}
2024-08-30 00:35:19,086 INFO    MainThread:1294756 [wandb_setup.py:_flush():77] Applying setup settings: {'_disable_service': False}
2024-08-30 00:35:19,086 INFO    MainThread:1294756 [wandb_setup.py:_flush():77] Inferring run settings from compute environment: {'program_relpath': 'de_rnn.py', 'program_abspath': '/home/rsw0/Desktop/yolanda/temp/CogModRNN/de_rnn.py', 'program': '/home/rsw0/Desktop/yolanda/temp/CogModRNN/de_rnn.py'}
2024-08-30 00:35:19,086 INFO    MainThread:1294756 [wandb_setup.py:_flush():77] Applying login settings: {}
2024-08-30 00:35:19,086 INFO    MainThread:1294756 [wandb_init.py:_log_setup():524] Logging user logs to /home/rsw0/Desktop/yolanda/temp/CogModRNN/wandb/run-20240830_003519-uv4owkrs/logs/debug.log
2024-08-30 00:35:19,086 INFO    MainThread:1294756 [wandb_init.py:_log_setup():525] Logging internal logs to /home/rsw0/Desktop/yolanda/temp/CogModRNN/wandb/run-20240830_003519-uv4owkrs/logs/debug-internal.log
2024-08-30 00:35:19,086 INFO    MainThread:1294756 [wandb_init.py:init():607] calling init triggers
2024-08-30 00:35:19,086 INFO    MainThread:1294756 [wandb_init.py:init():614] wandb.init called with sweep_config: {}
config: {'latent_size': 8, 'update_mlp_shape': [8, 8], 'choice_mlp_shape': [8, 8], 'beta_scale': 10.0, 'penalty_scale': 1e-05}
2024-08-30 00:35:19,086 INFO    MainThread:1294756 [wandb_init.py:init():657] starting backend
2024-08-30 00:35:19,086 INFO    MainThread:1294756 [wandb_init.py:init():661] setting up manager
2024-08-30 00:35:19,087 INFO    MainThread:1294756 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-08-30 00:35:19,088 INFO    MainThread:1294756 [wandb_init.py:init():669] backend started and connected
2024-08-30 00:35:19,091 INFO    MainThread:1294756 [wandb_init.py:init():767] updated telemetry
2024-08-30 00:35:19,108 INFO    MainThread:1294756 [wandb_init.py:init():800] communicating run to backend with 90.0 second timeout
2024-08-30 00:35:19,216 ERROR   MainThread:1294756 [wandb_init.py:init():826] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
2024-08-30 00:35:19,216 ERROR   MainThread:1294756 [wandb_init.py:init():1238] error in wandb.init()
Traceback (most recent call last):
  File "/home/rsw0/miniforge3/envs/yolanda/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1228, in init
    return wi.init()
  File "/home/rsw0/miniforge3/envs/yolanda/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 832, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
2024-08-30 00:35:20,305 WARNING MsgRouterThr:1294756 [router.py:message_loop():77] message_loop has been closed
