
Training with beta_scale: 1e-05 and penalty_scale: 1e-10



Step 40 of 500; Loss: 1.2351e+05. Model Size: 5684 (Time: 43.3s)
Exception ignored in: <function _xla_gc_callback at 0x7495c610cee0>
Traceback (most recent call last):
  File "/home/rsw0/miniforge3/envs/yolanda/lib/python3.9/site-packages/jax/_src/lib/__init__.py", line 96, in _xla_gc_callback
    def _xla_gc_callback(*args):


